# Generated by Django 6.0.2 on 2026-02-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_tenant_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='domain',
            new_name='company',
        ),
    ]
